version: "2"
run:
  timeout: 10m
  build-tags:
    - rpctest
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - dupword
    - durationcheck
    - errchkjson
    - errorlint
    - godoclint
    - govet
    - grouper
    - ineffassign
    - misspell
    - nilerr
    - nosprintfhostport
    - reassign
    - rowserrcheck
    - staticcheck
    - tparallel
    - unconvert
    - unused
    - usetesting
  settings:
    staticcheck:
      checks:
          - S1*
    godoclint:
      default: none
      enable:
        - pkg-doc
        - start-with-name
        - deprecated
        - no-unused-link
formatters:
  enable:
    - gofmt
    - goimports
