// Copyright (c) 2026 The Decred developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package secp256k1

import (
	mrand "math/rand"
	"testing"
	"time"
)

// assertSameReceiver ensures the wrapper preserves the chaining API.
func assertSameReceiver(t *testing.T, got, want *FieldVal) {
	t.Helper()

	if got != want {
		t.Fatalf("method returned %p, want %p", got, want)
	}
}

// assertFieldValMatchesImpl ensures the wrapper and underlying implementation
// produce identical normalized values.
func assertFieldValMatchesImpl(t *testing.T, got *FieldVal, want *fieldImpl) {
	t.Helper()

	got.Normalize()
	want.Normalize()

	if !got.impl.Equals(want) {
		t.Fatalf("mismatched values:\n got: %v\nwant: %v", got.impl.String(),
			want.String())
	}
}

// randBytes32 returns a 32-byte array created from a random value generated by
// the passed rng.
func randBytes32(t *testing.T, rng *mrand.Rand) [32]byte {
	t.Helper()

	var buf [32]byte
	if _, err := rng.Read(buf[:]); err != nil {
		t.Fatalf("failed to read random: %v", err)
	}

	return buf
}

// randFieldValAndImplElement returns a [FieldVal] and [fieldImpl] element
// created from a random value generated by the passed rng.
func randFieldValAndImplElement(t *testing.T, rng *mrand.Rand) (*FieldVal, *fieldImpl) {
	t.Helper()

	buf := randBytes32(t, rng)

	// Create and return a field value.
	var fv FieldVal
	fv.SetBytes(&buf)
	fv.Normalize()

	var elem fieldImpl
	elem.SetBytes(&buf)
	elem.Normalize()

	return &fv, &elem
}

// TestFieldValWrapper ensures the wrapper around the architecture-specific
// field implementation works as intended.  It intentionally does NOT perform
// exhaustive testing of each of the methods since that is handled by each
// implementation.  Instead, it focuses on making sure the wrapper returns the
// same result as the underlying implementation and the methods that involve
// chaining return the same wrapped instance.
func TestFieldValWrapper(t *testing.T) {
	// Use a unique random seed for each test instance and log it if the tests
	// fail.
	seed := time.Now().Unix()
	rng := mrand.New(mrand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	assertEqBool := func(got, want bool) {
		t.Helper()

		if got != want {
			t.Fatalf("mismatched result -- got %v, want %v", got, want)
		}
	}

	assertEqUint32 := func(got, want uint32) {
		t.Helper()

		if got != want {
			t.Fatalf("mismatched result -- got %v, want %v", got, want)
		}
	}

	for i := 0; i < 25; i++ {
		// Create a field val and underlying implementation element from the
		// same random value and immediately ensure they match because the
		// helper depends on [FieldVal.SetBytes].  This also indirectly tests
		// [FieldVal.Normalize].
		fv, impl := randFieldValAndImplElement(t, rng)
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.String] forwards properly.  This is done early to
		// avoid misleading output if anything were to fail later.
		if got := fv.String(); got != impl.String() {
			t.Errorf("mismatched string -- got %v, want %v", got, impl.String())
		}

		// Ensure [FieldVal.Normalize] forwards and chains properly.
		//
		// The output of the helper is already normalized, so multiply to
		// potentially create internal overflow (for implementations where it
		// applies).
		//
		// Note that this relies on the correctness of [FieldVal.MulInt], but
		// that is tested later, so it's safe.
		//
		// This could be done after [FieldVal.MulInt] is tested to avoid that,
		// but it is done early to avoid what could potentially be very
		// confusing output otherwise since most of the other tests rely on
		// normalization.
		fv.MulInt(20)
		impl.MulInt(20)
		assertSameReceiver(t, fv.Normalize(), fv)
		assertFieldValMatchesImpl(t, fv, impl.Normalize())

		// ----------------------
		// Construction wrappers.
		// ----------------------

		// Ensure [FieldVal.Set] forwards properly.
		fvSet, implSet := new(FieldVal).Set(fv), new(fieldImpl).Set(impl)
		assertFieldValMatchesImpl(t, fvSet, implSet)

		// Ensure [FieldVal.Zero] forwards properly.
		fv.Zero()
		impl.Zero()
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.SetBytes] and [FieldVal.SetByteSlice] forward
		// properly with a random value.
		b32 := randBytes32(t, rng)
		assertEqUint32(fv.SetBytes(&b32), impl.SetBytes(&b32))
		assertFieldValMatchesImpl(t, fv, impl)
		assertEqBool(fv.SetByteSlice(b32[:]), impl.SetByteSlice(b32[:]))
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.SetBytes] and [FieldVal.SetByteSlice] forward
		// properly with the field prime to ensure overflow is forwarded
		// properly.
		curveParams.P.FillBytes(b32[:])
		assertEqUint32(fv.SetBytes(&b32), impl.SetBytes(&b32))
		assertFieldValMatchesImpl(t, fv, impl)
		assertEqBool(fv.SetByteSlice(b32[:]), impl.SetByteSlice(b32[:]))
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.SetBytes] and [FieldVal.SetByteSlice] forward
		// properly with the group order to ensure non-overflow is forwarded
		// properly.
		curveParams.N.FillBytes(b32[:])
		assertEqUint32(fv.SetBytes(&b32), impl.SetBytes(&b32))
		assertFieldValMatchesImpl(t, fv, impl)
		assertEqBool(fv.SetByteSlice(b32[:]), impl.SetByteSlice(b32[:]))
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.SetInt] forwards and chains properly.
		assertSameReceiver(t, fv.SetInt(1), fv)
		assertFieldValMatchesImpl(t, fv, impl.SetInt(1))

		// ----------------------
		// Output bytes wrappers.
		// ----------------------

		// Generate new random value since the instances were clobbered above.
		fv, impl = randFieldValAndImplElement(t, rng)

		// Ensure [FieldVal.PutBytesUnchecked] forwards properly.
		var fvBuf32, implBuf32 [32]byte
		fv.PutBytesUnchecked(fvBuf32[:])
		impl.PutBytesUnchecked(implBuf32[:])
		if fvBuf32 != implBuf32 {
			t.Fatalf("mismatched result -- got %x, want %x", fvBuf32, implBuf32)
		}

		// Ensure [FieldVal.PutBytes] forwards properly.
		fvBuf32, implBuf32 = [32]byte{}, [32]byte{}
		fv.PutBytes(&fvBuf32)
		impl.PutBytes(&implBuf32)
		if fvBuf32 != implBuf32 {
			t.Fatalf("mismatched result -- got %x, want %x", fvBuf32, implBuf32)
		}

		// Ensure [FieldVal.Bytes] forwards properly.
		fvBuf32, implBuf32 = *fv.Bytes(), *impl.Bytes()
		if fvBuf32 != implBuf32 {
			t.Fatalf("mismatched result -- got %x, want %x", fvBuf32, implBuf32)
		}

		// --------------------
		// Comparison wrappers.
		// --------------------

		// Ensure [FieldVal.IsZeroBit] forwards properly.
		assertEqUint32(fv.IsZeroBit(), impl.IsZeroBit())

		// Ensure [FieldVal.IsZero] forwards properly.
		assertEqBool(fv.IsZero(), impl.IsZero())

		// Ensure [FieldVal.IsOneBit] forwards properly.
		assertEqUint32(fv.IsOneBit(), impl.IsOneBit())

		// Ensure [FieldVal.IsOne] forwards properly.
		assertEqBool(fv.IsOne(), impl.IsOne())

		// Ensure [FieldVal.IsOddBit] forwards properly.
		assertEqUint32(fv.IsOddBit(), impl.IsOddBit())

		// Ensure [FieldVal.IsOdd] forwards properly.
		assertEqBool(fv.IsOdd(), impl.IsOdd())

		// Ensure [FieldVal.Equals] forwards properly.
		fv2, impl2 := randFieldValAndImplElement(t, rng)
		assertEqBool(fv.Equals(fv2), impl.Equals(impl2))

		// Ensure [FieldVal.IsGtOrEqPrimeMinusOrder] forwards properly.
		assertEqBool(fv.IsGtOrEqPrimeMinusOrder(), impl.IsGtOrEqPrimeMinusOrder())

		// --------------------
		// Arithmetic wrappers.
		// --------------------

		// Ensure [FieldVal.NegateVal] forwards and chains properly.
		assertSameReceiver(t, fv.NegateVal(fv2, 1), fv)
		assertFieldValMatchesImpl(t, fv, impl.NegateVal(impl2, 1))

		// Ensure [FieldVal.Negate] forwards and chains properly.
		assertSameReceiver(t, fv.Negate(1), fv)
		assertFieldValMatchesImpl(t, fv, impl.Negate(1))

		// Ensure [FieldVal.AddInt] forwards and chains properly.
		assertSameReceiver(t, fv.AddInt(1), fv)
		assertFieldValMatchesImpl(t, fv, impl.AddInt(1))

		// Ensure [FieldVal.Add] forwards and chains properly.
		assertSameReceiver(t, fv.Add(fv2), fv)
		assertFieldValMatchesImpl(t, fv, impl.Add(impl2))

		// Ensure [FieldVal.Add2] forwards and chains properly.
		assertSameReceiver(t, fv.Add2(fv, fv2), fv)
		assertFieldValMatchesImpl(t, fv, impl.Add2(impl, impl2))

		// Ensure [FieldVal.MulBy2] forwards and chains properly.
		assertSameReceiver(t, fv.MulBy2(), fv)
		assertFieldValMatchesImpl(t, fv, impl.MulBy2())

		// Ensure [FieldVal.MulBy3] forwards and chains properly.
		assertSameReceiver(t, fv.MulBy3(), fv)
		assertFieldValMatchesImpl(t, fv, impl.MulBy3())

		// Ensure [FieldVal.MulBy4] forwards and chains properly.
		assertSameReceiver(t, fv.MulBy4(), fv)
		assertFieldValMatchesImpl(t, fv, impl.MulBy4())

		// Ensure [FieldVal.MulBy8] forwards and chains properly.
		assertSameReceiver(t, fv.MulBy8(), fv)
		assertFieldValMatchesImpl(t, fv, impl.MulBy8())

		// Ensure [FieldVal.MulInt] forwards and chains properly.
		assertSameReceiver(t, fv.MulInt(16), fv)
		assertFieldValMatchesImpl(t, fv, impl.MulInt(16))

		// Ensure [FieldVal.Mul] forwards and chains properly.
		assertSameReceiver(t, fv.Mul(fv2), fv)
		assertFieldValMatchesImpl(t, fv, impl.Mul(impl2))

		// Ensure [FieldVal.Mul2] forwards and chains properly.
		assertSameReceiver(t, fv.Mul2(fv, fv2), fv)
		assertFieldValMatchesImpl(t, fv, impl.Mul2(impl, impl2))

		// Ensure [FieldVal.SquareRootVal] forwards properly.
		assertEqBool(fv.SquareRootVal(fv2), impl.SquareRootVal(impl2))
		assertFieldValMatchesImpl(t, fv, impl)

		// Ensure [FieldVal.Square] forwards and chains properly.
		assertSameReceiver(t, fv.Square(), fv)
		assertFieldValMatchesImpl(t, fv, impl.Square())

		// Ensure [FieldVal.SquareVal] forwards and chains properly.
		assertSameReceiver(t, fv.SquareVal(fv2), fv)
		assertFieldValMatchesImpl(t, fv, impl.SquareVal(impl2))

		// Ensure [FieldVal.Inverse] forwards and chains properly.
		assertSameReceiver(t, fv.Inverse(), fv)
		assertFieldValMatchesImpl(t, fv, impl.Inverse())
	}
}
