// Copyright (c) 2020-2026 The Decred developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package secp256k1

import (
	"bytes"
	"fmt"
	"math/big"
	"math/rand"
	"reflect"
	"testing"
	"time"
)

// mustModNScalarWithOverflow converts the passed hex string into a [ModNScalar]
// and will panic if there is an error.  Values that overflow are NOT treated as
// an error.
//
// This is only provided for the hard-coded constants so errors in the source
// code can be detected.  It will only (and must only) be called with hard-coded
// values.
func mustModNScalarWithOverflow(s string) *ModNScalar {
	return mustModNScalarInternal(s, true)
}

// randModNScalar returns a mod N scalar created from a random value generated
// by the passed rng.
func randModNScalar(t *testing.T, rng *rand.Rand) *ModNScalar {
	t.Helper()

	var buf [32]byte
	if _, err := rng.Read(buf[:]); err != nil {
		t.Fatalf("failed to read random: %v", err)
	}

	// Create and return a mod N scalar.
	var modNVal ModNScalar
	modNVal.SetBytes(&buf)
	return &modNVal
}

// randIntAndModNScalar returns a big integer and mod N scalar both created from
// the same random value generated by the passed rng.
func randIntAndModNScalar(t *testing.T, rng *rand.Rand) (*big.Int, *ModNScalar) {
	t.Helper()

	var buf [32]byte
	if _, err := rng.Read(buf[:]); err != nil {
		t.Fatalf("failed to read random: %v", err)
	}

	// Create and return both a big integer and a mod N scalar.
	bigIntVal := new(big.Int).SetBytes(buf[:])
	bigIntVal.Mod(bigIntVal, curveParams.N)
	var modNVal ModNScalar
	modNVal.SetBytes(&buf)
	return bigIntVal, &modNVal
}

// TestModNScalarZero ensures that zeroing a scalar modulo the group order works
// as expected.
func TestModNScalarZero(t *testing.T) {
	valHex := "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5"
	s := mustModNScalar(valHex)
	s.Zero()
	for idx, rawInt := range s.n {
		if rawInt != 0 {
			t.Errorf("internal integer at index #%d is not zero - got %d", idx,
				rawInt)
		}
	}
}

// TestModNScalarIsZero ensures that checking if a scalar is zero via IsZero and
// IsZeroBit works as expected.
func TestModNScalarIsZero(t *testing.T) {
	var s ModNScalar
	if !s.IsZero() {
		t.Errorf("new scalar is not zero - got %v (rawints %x)", s, s.n)
	}
	if s.IsZeroBit() != 1 {
		t.Errorf("new scalar is not zero - got %v (rawints %x)", s, s.n)
	}

	s.SetInt(1)
	if s.IsZero() {
		t.Errorf("claims zero for nonzero scalar - got %v (rawints %x)", s, s.n)
	}
	if s.IsZeroBit() == 1 {
		t.Errorf("claims zero for nonzero scalar - got %v (rawints %x)", s, s.n)
	}

	s.SetInt(0)
	if !s.IsZero() {
		t.Errorf("claims nonzero for zero scalar - got %v (rawints %x)", s, s.n)
	}
	if s.IsZeroBit() != 1 {
		t.Errorf("claims nonzero for zero scalar - got %v (rawints %x)", s, s.n)
	}

	s.SetInt(1)
	s.Zero()
	if !s.IsZero() {
		t.Errorf("claims nonzero for zero scalar - got %v (rawints %x)", s, s.n)
	}
	if s.IsZeroBit() != 1 {
		t.Errorf("claims nonzero for zero scalar - got %v (rawints %x)", s, s.n)
	}
}

// TestModNScalarSetInt ensures that setting a scalar to various native integers
// works as expected.
func TestModNScalarSetInt(t *testing.T) {
	tests := []struct {
		name     string    // test description
		in       uint32    // test value
		expected [4]uint64 // expected limbs
	}{{
		name:     "zero",
		in:       0,
		expected: [4]uint64{0, 0, 0, 0},
	}, {
		name:     "five",
		in:       5,
		expected: [4]uint64{5, 0, 0, 0},
	}, {
		name:     "max uint8 (2^8 - 1)",
		in:       255,
		expected: [4]uint64{255, 0, 0, 0},
	}, {
		name:     "max uint16 (2^16 - 1)",
		in:       65535,
		expected: [4]uint64{65535, 0, 0, 0},
	}, {
		name:     "max uint32 (2^32 - 1)",
		in:       4294967295,
		expected: [4]uint64{4294967295, 0, 0, 0},
	}}

	for _, test := range tests {
		s := new(ModNScalar).SetInt(test.in)
		if !reflect.DeepEqual(s.n, test.expected) {
			t.Errorf("%s: wrong result\ngot: %v\nwant: %v", test.name, s.n,
				test.expected)
			continue
		}
	}
}

// TestModNScalarSetBytes ensures that setting a scalar to a 256-bit big-endian
// unsigned integer via both the slice and array methods works as expected for
// edge cases.  Random cases are tested via the various other tests.
func TestModNScalarSetBytes(t *testing.T) {
	tests := []struct {
		name     string    // test description
		in       string    // hex encoded test value
		expected [4]uint64 // expected raw ints
		overflow bool      // expected overflow result
	}{{
		name:     "zero",
		in:       "00",
		expected: [4]uint64{0, 0, 0, 0},
		overflow: false,
	}, {
		name:     "one (only limb zero set)",
		in:       "01",
		expected: [4]uint64{1, 0, 0, 0},
		overflow: false,
	}, {
		name:     "2^64 - 1 (limb zero all ones)",
		in:       "ffffffffffffffff",
		expected: [4]uint64{0xffffffffffffffff, 0, 0, 0},
		overflow: false,
	}, {
		name:     "2^64 (limb one low bit)",
		in:       "010000000000000000",
		expected: [4]uint64{0, 1, 0, 0},
		overflow: false,
	}, {
		name:     "2^128 - 1 (limbs zero and one all ones)",
		in:       "ffffffffffffffffffffffffffffffff",
		expected: [4]uint64{0xffffffffffffffff, 0xffffffffffffffff, 0, 0},
		overflow: false,
	}, {
		name:     "2^128 (limb two low bit)",
		in:       "0100000000000000000000000000000000",
		expected: [4]uint64{0, 0, 1, 0},
		overflow: false,
	}, {
		name: "2^192 - 1 (limbs zero, one, and two all ones)",
		in:   "ffffffffffffffffffffffffffffffffffffffffffffffff",
		expected: [4]uint64{
			0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0,
		},
		overflow: false,
	}, {
		name:     "2^192 (limb three low bit)",
		in:       "01000000000000000000000000000000000000000000000000",
		expected: [4]uint64{0, 0, 0, 1},
		overflow: false,
	}, {
		name:     "2^255 (limb three high bit)",
		in:       "8000000000000000000000000000000000000000000000000000000000000000",
		expected: [4]uint64{0, 0, 0, 0x8000000000000000},
		overflow: false,
	}, {
		name: "distinct value in every limb (verifies limb ordering)",
		in:   "0123456789abcdeffedcba98765432100f1e2d3c4b5a69788796a5b4c3d2e1f0",
		expected: [4]uint64{
			0x08796a5b4c3d2e1f0, 0x0f1e2d3c4b5a6978, 0xfedcba9876543210,
			0x0123456789abcdef,
		},
		overflow: false,
	}, {
		name:     "group order (aka 0)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		expected: [4]uint64{0, 0, 0, 0},
		overflow: true,
	}, {
		name: "group order - 1 (limb zero one below prime, upper limbs maxed)",
		in:   "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: [4]uint64{
			0xbfd25e8cd0364140, 0xbaaedce6af48a03b, 0xfffffffffffffffe,
			0xffffffffffffffff,
		},
		overflow: false,
	}, {
		name:     "group order + 1 (aka 1, overflow in limb zero)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142",
		expected: [4]uint64{1, 0, 0, 0},
		overflow: true,
	}, {
		name:     "group order limb zero",
		in:       "bfd25e8cd0364141",
		expected: [4]uint64{0xbfd25e8cd0364141, 0, 0, 0},
		overflow: false,
	}, {
		name:     "group order limbs zero and one",
		in:       "baaedce6af48a03bbfd25e8cd0364141",
		expected: [4]uint64{0xbfd25e8cd0364141, 0xbaaedce6af48a03b, 0, 0},
		overflow: false,
	}, {
		name: "group order limbs zero, one, and two",
		in:   "fffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		expected: [4]uint64{
			0xbfd25e8cd0364141, 0xbaaedce6af48a03b, 0xfffffffffffffffe, 0,
		},
		overflow: false,
	}, {
		name:     "group order + 2^64 (overflow in limb one)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03cbfd25e8cd0364141",
		expected: [4]uint64{0, 1, 0, 0},
		overflow: true,
	}, {
		name:     "group order + 2^128 (overflow in limb two)",
		in:       "ffffffffffffffffffffffffffffffffbaaedce6af48a03bbfd25e8cd0364141",
		expected: [4]uint64{0, 0, 1, 0},
		overflow: true,
	}, {
		name:     "2^256 - 1 (max input)",
		in:       "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
		expected: [4]uint64{0x402da1732fc9bebe, 0x4551231950b75fc4, 1, 0},

		overflow: true,
	}, {
		name: "(group order - 1) * 2 NOT mod N, truncated >32 bytes",
		in:   "01fffffffffffffffffffffffffffffffd755db9cd5e9140777fa4bd19a06c8284",
		expected: [4]uint64{
			0x777fa4bd19a06c82, 0xfd755db9cd5e9140, 0xffffffffffffffff,
			0x01ffffffffffffff,
		},
		overflow: false,
	}, {
		name: "alternating bits (spans all limbs)",
		in:   "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: [4]uint64{
			0xa5a5a5a5a5a5a5a5, 0xa5a5a5a5a5a5a5a5, 0xa5a5a5a5a5a5a5a5,
			0xa5a5a5a5a5a5a5a5,
		},
		overflow: false,
	}, {
		name: "alternating bits 2 (spans all limbs)",
		in:   "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: [4]uint64{
			0x5a5a5a5a5a5a5a5a, 0x5a5a5a5a5a5a5a5a, 0x5a5a5a5a5a5a5a5a,
			0x5a5a5a5a5a5a5a5a,
		},
		overflow: false,
	}}

	for _, test := range tests {
		inBytes := hexToBytes(test.in)

		// Ensure setting the bytes via the slice method works as expected.
		var s ModNScalar
		overflow := s.SetByteSlice(inBytes)
		if !reflect.DeepEqual(s.n, test.expected) {
			t.Errorf("%s: unexpected result\ngot: %x\nwant: %x", test.name, s.n,
				test.expected)
			continue
		}

		// Ensure the setting the bytes via the slice method produces the
		// expected overflow result.
		if overflow != test.overflow {
			t.Errorf("%s: unexpected overflow -- got: %v, want: %v", test.name,
				overflow, test.overflow)
			continue
		}

		// Ensure setting the bytes via the array method works as expected.
		var s2 ModNScalar
		var b32 [32]byte
		truncatedInBytes := inBytes
		if len(truncatedInBytes) > 32 {
			truncatedInBytes = truncatedInBytes[:32]
		}
		copy(b32[32-len(truncatedInBytes):], truncatedInBytes)
		overflow = s2.SetBytes(&b32) != 0
		if !reflect.DeepEqual(s2.n, test.expected) {
			t.Errorf("%s: unexpected result\ngot: %x\nwant: %x", test.name,
				s2.n, test.expected)
			continue
		}

		// Ensure the setting the bytes via the array method produces the
		// expected overflow result.
		if overflow != test.overflow {
			t.Errorf("%s: unexpected overflow -- got: %v, want: %v", test.name,
				overflow, test.overflow)
			continue
		}
	}
}

// TestModNScalarBytes ensures that retrieving the bytes for a 256-bit
// big-endian unsigned integer via the various methods works as expected for
// edge cases.  Random cases are tested via the various other tests.
func TestModNScalarBytes(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded test value
		expected string // expected hex encoded bytes
		overflow bool   // expected overflow result
	}{{
		name:     "zero",
		in:       "0",
		expected: "0000000000000000000000000000000000000000000000000000000000000000",
	}, {
		name:     "group order (aka 0)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		expected: "0000000000000000000000000000000000000000000000000000000000000000",
	}, {
		name:     "group order - 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
	}, {
		name:     "group order + 1 (aka 1, overflow in limb zero)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142",
		expected: "0000000000000000000000000000000000000000000000000000000000000001",
	}, {
		name:     "group order limb zero",
		in:       "d0364141",
		expected: "00000000000000000000000000000000000000000000000000000000d0364141",
	}, {
		name:     "group order limb zero and one",
		in:       "bfd25e8cd0364141",
		expected: "000000000000000000000000000000000000000000000000bfd25e8cd0364141",
	}, {
		name:     "group order limbs zero, one, and two",
		in:       "af48a03bbfd25e8cd0364141",
		expected: "0000000000000000000000000000000000000000af48a03bbfd25e8cd0364141",
	}, {
		name:     "overflow in limb one",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8dd0364141",
		expected: "0000000000000000000000000000000000000000000000000000000100000000",
	}, {
		name:     "overflow in limb two",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03cbfd25e8cd0364141",
		expected: "0000000000000000000000000000000000000000000000010000000000000000",
	}, {
		name:     "overflow in limb three",
		in:       "fffffffffffffffffffffffffffffffebaaedce7af48a03bbfd25e8cd0364141",
		expected: "0000000000000000000000000000000000000001000000000000000000000000",
	}, {
		name:     "overflow in limb four",
		in:       "ffffffffffffffffffffffffffffffffbaaedce6af48a03bbfd25e8cd0364141",
		expected: "0000000000000000000000000000000100000000000000000000000000000000",
	}, {
		name:     "alternating bits",
		in:       "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
	}, {
		name:     "alternating bits 2",
		in:       "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
	}}

	for _, test := range tests {
		s := mustModNScalarWithOverflow(test.in)
		expected := hexToBytes(test.expected)

		// Ensure getting the bytes works as expected.
		gotBytes := s.Bytes()
		if !bytes.Equal(gotBytes[:], expected) {
			t.Errorf("%s: unexpected result\ngot: %x\nwant: %x", test.name,
				gotBytes, expected)
			continue
		}

		// Ensure getting the bytes directly into an array works as expected.
		var b32 [32]byte
		s.PutBytes(&b32)
		if !bytes.Equal(b32[:], expected) {
			t.Errorf("%s: unexpected result\ngot: %x\nwant: %x", test.name,
				b32, expected)
			continue
		}

		// Ensure getting the bytes directly into a slice works as expected.
		var buffer [64]byte
		s.PutBytesUnchecked(buffer[:])
		if !bytes.Equal(buffer[:32], expected) {
			t.Errorf("%s: unexpected result\ngot: %x\nwant: %x", test.name,
				buffer[:32], expected)
			continue
		}
	}
}

// TestModNScalarIsOdd ensures that checking if a scalar is odd works as
// expected.
func TestModNScalarIsOdd(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded value
		expected bool   // expected oddness
	}{{
		name:     "zero",
		in:       "0",
		expected: false,
	}, {
		name:     "one",
		in:       "1",
		expected: true,
	}, {
		name:     "two",
		in:       "2",
		expected: false,
	}, {
		name:     "2^32 - 1",
		in:       "ffffffff",
		expected: true,
	}, {
		name:     "2^64 - 2",
		in:       "fffffffffffffffe",
		expected: false,
	}, {
		name:     "group order (aka 0)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		expected: false,
	}, {
		name:     "group order + 1 (aka 1)",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142",
		expected: true,
	}}

	for _, test := range tests {
		result := mustModNScalarWithOverflow(test.in).IsOdd()
		if result != test.expected {
			t.Errorf("%s: wrong result -- got: %v, want: %v", test.name,
				result, test.expected)
			continue
		}
	}
}

// TestModNScalarEquals ensures that checking two scalars for equality works as
// expected for edge cases.
func TestModNScalarEquals(t *testing.T) {
	tests := []struct {
		name     string // test description
		in1      string // hex encoded value
		in2      string // hex encoded value
		expected bool   // expected equality
	}{{
		name:     "0 == 0?",
		in1:      "0",
		in2:      "0",
		expected: true,
	}, {
		name:     "0 == 1?",
		in1:      "0",
		in2:      "1",
		expected: false,
	}, {
		name:     "1 == 0?",
		in1:      "1",
		in2:      "0",
		expected: false,
	}, {
		name:     "2^32 - 1 == 2^32 - 1?",
		in1:      "ffffffff",
		in2:      "ffffffff",
		expected: true,
	}, {
		name:     "2^64 - 1 == 2^64 - 2?",
		in1:      "ffffffffffffffff",
		in2:      "fffffffffffffffe",
		expected: false,
	}, {
		name:     "0 == group order?",
		in1:      "0",
		in2:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		expected: true,
	}, {
		name:     "1 == group order + 1?",
		in1:      "1",
		in2:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142",
		expected: true,
	}}

	for _, test := range tests {
		s1 := mustModNScalarWithOverflow(test.in1)
		s2 := mustModNScalarWithOverflow(test.in2)
		result := s1.Equals(s2)
		if result != test.expected {
			t.Errorf("%s: wrong result -- got: %v, want: %v", test.name, result,
				test.expected)
			continue
		}
	}
}

// TestModNScalarEqualsRandom ensures that scalars for random values works as
// expected.
func TestModNScalarEqualsRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Ensure a randomly-generated scalar equals itself.
		s := randModNScalar(t, rng)
		if !s.Equals(s) {
			t.Fatalf("failed equality check\nscalar in: %v", s)
		}

		// Flip a random bit in a random limb and ensure it's no longer equal.
		randomLimb := rng.Int31n(int32(len(s.n)))
		randomBit := uint64(1 << uint64(rng.Int63n(64)))
		s2 := new(ModNScalar).Set(s)
		s2.n[randomLimb] ^= randomBit
		if s2.Equals(s) {
			t.Fatalf("failed inequality check\nscalar in: %v", s2)
		}
	}
}

// TestModNScalarAdd ensures that adding two scalars works as expected for edge
// cases.
func TestModNScalarAdd(t *testing.T) {
	tests := []struct {
		name     string // test description
		in1      string // first hex encoded test value
		in2      string // second hex encoded test value
		expected string // expected hex encoded bytes
	}{{
		name:     "zero + one",
		in1:      "0",
		in2:      "1",
		expected: "1",
	}, {
		name:     "one + zero",
		in1:      "1",
		in2:      "0",
		expected: "1",
	}, {
		name:     "group order-1 + 1 (aka 0, overflow to order)",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "1",
		expected: "0",
	}, {
		name:     "group order (aka 0) + 1 (aka 1, gets reduced, no overflow)",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		in2:      "1",
		expected: "1",
	}, {
		name:     "group order-1 + 2 (aka 1, overflow in limb zero)",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "2",
		expected: "1",
	}, {
		name:     "overflow in limb one",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03abfd25e8cd0364141",
		in2:      "10000000000000001",
		expected: "1",
	}, {
		name:     "overflow in limb two",
		in1:      "fffffffffffffffffffffffffffffffdbaaedce6af48a03bbfd25e8cd0364141",
		in2:      "100000000000000000000000000000001",
		expected: "1",
	}, {
		name:     "overflow in limb three",
		in1:      "fffffffffffffffefffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		in2:      "1000000000000000000000000000000000000000000000001",
		expected: "1",
	}, {
		name:     "alternating bits",
		in1:      "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		in2:      "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "14551231950b75fc4402da1732fc9bebe",
	}, {
		name:     "alternating bits 2",
		in1:      "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		in2:      "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "14551231950b75fc4402da1732fc9bebe",
	}}

	for _, test := range tests {
		// Parse test hex.
		s1 := mustModNScalarWithOverflow(test.in1)
		s2 := mustModNScalarWithOverflow(test.in2)
		expected := mustModNScalar(test.expected)

		// Ensure the result has the expected value.
		s1.Add(s2)
		if !s1.Equals(expected) {
			t.Errorf("%s: unexpected result\ngot: %v\nwant: %v", test.name,
				s1, expected)
			continue
		}
	}
}

// TestModNScalarAddRandom ensures that adding two scalars together for random
// values works as expected by also performing the same operation with big ints
// and comparing the results.
func TestModNScalarAddRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Generate two big integer and mod n scalar pairs.
		bigIntVal1, modNVal1 := randIntAndModNScalar(t, rng)
		bigIntVal2, modNVal2 := randIntAndModNScalar(t, rng)

		// Calculate the sum of the values using big ints.
		bigIntResult := new(big.Int).Add(bigIntVal1, bigIntVal2)
		bigIntResult.Mod(bigIntResult, curveParams.N)

		// Calculate the sum of the values using mod n scalars.
		modNValResult := new(ModNScalar).Add2(modNVal1, modNVal2)

		// Ensure they match.
		bigIntResultHex := fmt.Sprintf("%064x", bigIntResult)
		modNResultHex := fmt.Sprintf("%v", modNValResult)
		if bigIntResultHex != modNResultHex {
			t.Fatalf("mismatched add\nbig int in 1: %x\nbig int in 2: %x\n"+
				"scalar in 1: %v\nscalar in 2: %v\nbig int result: %x\nscalar "+
				"result %v", bigIntVal1, bigIntVal2, modNVal1, modNVal2,
				bigIntResult, modNValResult)
		}
	}
}

// TestModNScalarMul ensures that multiplying two scalars together works as
// expected for edge cases.
func TestModNScalarMul(t *testing.T) {
	tests := []struct {
		name     string // test description
		in1      string // first hex encoded value
		in2      string // second hex encoded value to multiply with
		expected string // expected hex encoded value
	}{{
		name:     "zero * zero",
		in1:      "0",
		in2:      "0",
		expected: "0",
	}, {
		name:     "one * zero",
		in1:      "1",
		in2:      "0",
		expected: "0",
	}, {
		name:     "one * one",
		in1:      "1",
		in2:      "1",
		expected: "1",
	}, {
		name:     "(group order-1) * 2",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "2",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f",
	}, {
		name:     "(group order-1) * 3",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "3",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413e",
	}, {
		name:     "(group order-1) * 4",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "4",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413d",
	}, {
		name:     "(group order-1) * (group order-1)",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		in2:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: "1",
	}, {
		name:     "slightly over group order",
		in1:      "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1",
		in2:      "2",
		expected: "1",
	}, {
		name:     "highest bit in limb zero squared",
		in1:      "8000000000000000",
		in2:      "8000000000000000",
		expected: "40000000000000000000000000000000",
	}, {
		name:     "highest bit in limb one squared",
		in1:      "80000000000000000000000000000000",
		in2:      "80000000000000000000000000000000",
		expected: "4000000000000000000000000000000000000000000000000000000000000000",
	}, {
		name:     "highest bit in limb two squared",
		in1:      "800000000000000000000000000000000000000000000000",
		in2:      "800000000000000000000000000000000000000000000000",
		expected: "515448c6542dd7f1100b685ccbf26fafc0000000000000000000000000000000",
	}, {
		name:     "highest bit in limb three squared",
		in1:      "8000000000000000000000000000000000000000000000000000000000000000",
		in2:      "8000000000000000000000000000000000000000000000000000000000000000",
		expected: "2759c7356071a6f179a5fd7916f341f19d0525b0839f3e1e225b3c8519f5f450",
	}, {
		name:     "cross limb product 64x128",
		in1:      "10000000000000000",
		in2:      "100000000000000000000000000000000",
		expected: "1000000000000000000000000000000000000000000000000",
	}, {
		name:     "cross limb product 64x192",
		in1:      "10000000000000000",
		in2:      "1000000000000000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "cross limb product 128x192",
		in1:      "100000000000000000000000000000000",
		in2:      "1000000000000000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf0000000000000000",
	}, {
		name:     "group order (aka 0) * 3",
		in1:      "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
		in2:      "3",
		expected: "0",
	}, {
		name:     "overflow in limb four",
		in1:      "100000000000000000000000000000000",
		in2:      "100000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "overflow in limb five",
		in1:      "10000000000000000000000000000000000000000",
		in2:      "10000000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf0000000000000000",
	}, {
		name:     "overflow in limb six",
		in1:      "1000000000000000000000000000000000000000000000000",
		in2:      "1000000000000000000000000000000000000000000000000",
		expected: "4551231950b75fc4402da1732fc9bec04551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "overflow in limb seven",
		in1:      "100000000000000000000000000000000000000000000000000000000",
		in2:      "100000000000000000000000000000000000000000000000000000000",
		expected: "402da1732fc9bec09d671cd581c69bc59509b0b074ec0aea8f564d667ec7eb3c",
	}, {
		name:     "max limb * one",
		in1:      "ffffffffffffffff",
		in2:      "1",
		expected: "ffffffffffffffff",
	}, {
		name:     "max limb * max limb",
		in1:      "ffffffffffffffff",
		in2:      "ffffffffffffffff",
		expected: "fffffffffffffffe0000000000000001",
	}, {
		name:     "alternating bits",
		in1:      "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		in2:      "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "88edea3d29272800e7988455cfdf19b039dbfbb1c93b5b44a48c2ba462316838",
	}, {
		name:     "alternating bits 2",
		in1:      "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		in2:      "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "88edea3d29272800e7988455cfdf19b039dbfbb1c93b5b44a48c2ba462316838",
	}}

	for _, test := range tests {
		v1 := mustModNScalarWithOverflow(test.in1)
		v2 := mustModNScalarWithOverflow(test.in2)
		expected := mustModNScalar(test.expected)

		// Ensure multiplying two other values produces the expected result.
		result := new(ModNScalar).Mul2(v1, v2)
		if !result.Equals(expected) {
			t.Errorf("%s: wrong result\ngot: %v\nwant: %v", test.name, result,
				expected)
			continue
		}

		// Ensure self multiplying with another value also produces the expected
		// result.
		result2 := new(ModNScalar).Set(v1).Mul(v2)
		if !result2.Equals(expected) {
			t.Errorf("%s: wrong result\ngot: %v\nwant: %v", test.name, result2,
				expected)
			continue
		}
	}
}

// TestModNScalarMulRandom ensures that multiplying two scalars together for
// random values works as expected by also performing the same operation with
// big ints and comparing the results.
func TestModNScalarMulRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Generate two big integer and mod n scalar pairs.
		bigIntVal1, modNVal1 := randIntAndModNScalar(t, rng)
		bigIntVal2, modNVal2 := randIntAndModNScalar(t, rng)

		// Calculate the square of the value using big ints.
		bigIntResult := new(big.Int).Mul(bigIntVal1, bigIntVal2)
		bigIntResult.Mod(bigIntResult, curveParams.N)

		// Calculate the square of the value using mod n scalar.
		modNValResult := new(ModNScalar).Mul2(modNVal1, modNVal2)

		// Ensure they match.
		bigIntResultHex := fmt.Sprintf("%064x", bigIntResult)
		modNResultHex := fmt.Sprintf("%v", modNValResult)
		if bigIntResultHex != modNResultHex {
			t.Fatalf("mismatched mul\nbig int in 1: %x\nbig int in 2: %x\n"+
				"scalar in 1: %v\nscalar in 2: %v\nbig int result: %x\nscalar "+
				"result %v", bigIntVal1, bigIntVal2, modNVal1, modNVal2,
				bigIntResult, modNValResult)
		}
	}
}

// TestModNScalarSquare ensures that squaring scalars works as expected for edge
// cases.
func TestModNScalarSquare(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded test value
		expected string // expected hex encoded value
	}{{
		name:     "zero",
		in:       "0",
		expected: "0",
	}, {
		name:     "one",
		in:       "1",
		expected: "1",
	}, {
		name:     "over group order",
		in:       "0000000000000000000000000000000100000000000000000000000000000000",
		expected: "000000000000000000000000000000014551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "group order - 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: "0000000000000000000000000000000000000000000000000000000000000001",
	}, {
		name:     "group order + 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364142",
		expected: "1",
	}, {
		name:     "overflow in limb eight",
		in:       "100000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "overflow in limb nine",
		in:       "1000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf00000000",
	}, {
		name:     "overflow in limb ten",
		in:       "10000000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf0000000000000000",
	}, {
		name:     "overflow in limb eleven",
		in:       "100000000000000000000000000000000000000000000",
		expected: "14551231950b75fc4402da1732fc9bebf000000000000000000000000",
	}, {
		name:     "overflow in limb twelve",
		in:       "1000000000000000000000000000000000000000000000000",
		expected: "4551231950b75fc4402da1732fc9bec04551231950b75fc4402da1732fc9bebf",
	}, {
		name:     "overflow in limb thirteen",
		in:       "10000000000000000000000000000000000000000000000000000",
		expected: "50b75fc4402da1732fc9bec09d671cd51b343a1b66926b57d2a4c1c61536bda7",
	}, {
		name:     "overflow in limb fourteen",
		in:       "100000000000000000000000000000000000000000000000000000000",
		expected: "402da1732fc9bec09d671cd581c69bc59509b0b074ec0aea8f564d667ec7eb3c",
	}, {
		name:     "overflow in limb fifteen",
		in:       "1000000000000000000000000000000000000000000000000000000000000",
		expected: "2fc9bec09d671cd581c69bc5e697f5e41f12c33a0a7b6f4e3302b92ea029cecd",
	}, {
		name:     "alternating bits",
		in:       "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "fb0982c5761d1eac534247f2a7c3af186a134d709b977ca88300faad5eafe9bc",
	}, {
		name:     "alternating bits 2",
		in:       "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "9081c595b95b2d17c424a546144b25488104c5889d914635bc9d1a51859e1c19",
	}}

	for _, test := range tests {
		v := mustModNScalarWithOverflow(test.in)
		expected := mustModNScalar(test.expected)

		// Ensure squaring another value produces the expected result.
		result := new(ModNScalar).SquareVal(v)
		if !result.Equals(expected) {
			t.Errorf("%s: wrong result\ngot: %v\nwant: %v", test.name, result,
				expected)
			continue
		}

		// Ensure self squaring also produces the expected result.
		result2 := new(ModNScalar).Set(v).Square()
		if !result2.Equals(expected) {
			t.Errorf("%s: wrong result\ngot: %v\nwant: %v", test.name, result2,
				expected)
			continue
		}
	}
}

// TestModNScalarSquareRandom ensures that squaring scalars for random values
// works as expected by also performing the same operation with big ints and
// comparing the results.
func TestModNScalarSquareRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Generate big integer and mod n scalar with the same random value.
		bigIntVal, modNVal := randIntAndModNScalar(t, rng)

		// Calculate the square of the value using big ints.
		bigIntResult := new(big.Int).Mul(bigIntVal, bigIntVal)
		bigIntResult.Mod(bigIntResult, curveParams.N)

		// Calculate the square of the value using mod n scalar.
		modNValResult := new(ModNScalar).SquareVal(modNVal)

		// Ensure they match.
		bigIntResultHex := fmt.Sprintf("%064x", bigIntResult)
		modNResultHex := fmt.Sprintf("%v", modNValResult)
		if bigIntResultHex != modNResultHex {
			t.Fatalf("mismatched square\nbig int in: %x\nscalar in: %v\n"+
				"big int result: %x\nscalar result %v", bigIntVal, modNVal,
				bigIntResult, modNValResult)
		}
	}
}

// checkModNScalarNegateProps checks algebraic properties of scalar negation.
func checkModNScalarNegateProps(t *testing.T, val *ModNScalar) {
	t.Helper()

	negation := new(ModNScalar).NegateVal(val)

	// Ensure involution produces the original value.  That is -(-x) == x.
	involution := new(ModNScalar).Set(negation).Negate()
	if !involution.Equals(val) {
		t.Errorf("mismatched involution -- got: %v, want: %v", involution,
			val)
	}

	// Ensure x + (-x) == 0.
	sum := new(ModNScalar).Add2(val, negation)
	if !sum.IsZero() {
		t.Errorf("x + (-x) != 0 -- got: %v, want: 0", sum)
	}
}

// TestModNScalarNegate ensures that negating scalars works as expected for edge
// cases.
func TestModNScalarNegate(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded test value
		expected string // hex encoded expected result
	}{{
		name:     "zero",
		in:       "0",
		expected: "0",
	}, {
		name:     "one",
		in:       "1",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
	}, {
		name:     "two",
		in:       "2",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f",
	}, {
		name:     "three",
		in:       "3",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413e",
	}, {
		name:     "group order - 2",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f",
		expected: "2",
	}, {
		name:     "group order - 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: "1",
	}, {
		name:     "negation in limb one",
		in:       "0000000000000000000000000000000000000000000000010000000000000000",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03abfd25e8cd0364141",
	}, {
		name:     "negation in limb two",
		in:       "0000000000000000000000000000000100000000000000000000000000000000",
		expected: "fffffffffffffffffffffffffffffffdbaaedce6af48a03bbfd25e8cd0364141",
	}, {
		name:     "negation in limb three",
		in:       "0000000000000001000000000000000000000000000000000000000000000000",
		expected: "fffffffffffffffefffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
	}, {
		name:     "half group order (floor)",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0",
		expected: "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1",
	}, {
		name:     "half group order (ceil)",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1",
		expected: "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0",
	}, {
		name:     "alternating bits",
		in:       "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a591509374109a2fa961a2cb8e72a909b9c",
	}, {
		name:     "alternating bits 2",
		in:       "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a46054828c54ee45e16578043275dbe6e7",
	}}

	for _, test := range tests {
		s := mustModNScalarWithOverflow(test.in)
		expected := mustModNScalar(test.expected)

		// Ensure negating another value produces the expected result.
		result := new(ModNScalar).NegateVal(s)
		if !result.Equals(expected) {
			t.Errorf("%s: unexpected result -- got: %v, want: %v", test.name,
				result, expected)
			continue
		}

		// Ensure self negating also produces the expected result.
		result2 := new(ModNScalar).Set(s).Negate()
		if !result2.Equals(expected) {
			t.Errorf("%s: unexpected result -- got: %v, want: %v", test.name,
				result2, expected)
			continue
		}

		// Ensure algebraic properties with negation hold.
		checkModNScalarNegateProps(t, s)
	}
}

// TestModNScalarNegateRandom ensures that negating scalars for random values
// works as expected by also performing the same operation with big ints and
// comparing the results.
func TestModNScalarNegateRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Generate big integer and mod n scalar with the same random value.
		bigIntVal, modNVal := randIntAndModNScalar(t, rng)

		// Calculate the negation of the value using big ints.
		bigIntResult := new(big.Int).Neg(bigIntVal)
		bigIntResult.Mod(bigIntResult, curveParams.N)

		// Calculate the negation of the value using mod n scalar.
		modNValResult := new(ModNScalar).NegateVal(modNVal)

		// Ensure they match.
		bigIntResultHex := fmt.Sprintf("%064x", bigIntResult)
		modNResultHex := fmt.Sprintf("%v", modNValResult)
		if bigIntResultHex != modNResultHex {
			t.Fatalf("mismatched negate\nbig int in: %x\nscalar in: %v\n"+
				"big int result: %x\nscalar result %v", bigIntVal, modNVal,
				bigIntResult, modNValResult)
		}

		// Ensure algebraic properties with negation hold.
		checkModNScalarNegateProps(t, modNVal)
	}
}

// checkModNScalarInverseProps checks algebraic properties of the
// multiplicative modular inverse of scalars.
func checkModNScalarInverseProps(t *testing.T, val *ModNScalar) {
	t.Helper()

	// Exception for 0 which does not have a modular multiplicative inverse.
	if val.IsZero() {
		return
	}

	inverse := new(ModNScalar).InverseValNonConst(val)

	// Ensure x * x^-1 ≡ 1 (mod N).
	product := new(ModNScalar).Mul2(val, inverse)
	one := new(ModNScalar).SetInt(1)
	if !product.Equals(one) {
		t.Errorf("x * x^-1 != 1 (mod N) -- got: %v, want: %v", product, one)
	}

	// Ensure (x^-1)^-1 == x.
	doubleInv := new(ModNScalar).InverseValNonConst(inverse)
	if !doubleInv.Equals(val) {
		t.Errorf("(x^-1)^-1 != x (mod N) -- got: %v, want: %v", doubleInv, val)
	}
}

// TestModNScalarInverseNonConst ensures that calculating the multiplicative
// inverse of scalars in *non-constant* time works as expected for edge cases.
func TestModNScalarInverseNonConst(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded test value
		expected string // hex encoded expected result
	}{{
		name:     "zero",
		in:       "0",
		expected: "0",
	}, {
		name:     "one",
		in:       "1",
		expected: "1",
	}, {
		name:     "two",
		in:       "2",
		expected: "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1",
	}, {
		name:     "group order - 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
	}, {
		name:     "group order - 2",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f",
		expected: "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0",
	}, {
		name:     "inverse carry in limb one",
		in:       "0000000000000000000000000000000000000000000000010000000000000000",
		expected: "4b0dff665588b13effffffffffffffffa09f710af01555259d4ad302583de6dc",
	}, {
		name:     "inverse carry in limb two",
		in:       "0000000000000000000000000000000100000000000000000000000000000000",
		expected: "50a51ac834b9ec244b0dff665588b13e9984d5b3cf80ef0fd6a23766a3ee9f22",
	}, {
		name:     "inverse carry in limb three",
		in:       "0000000000000001000000000000000000000000000000000000000000000000",
		expected: "897f30c127cfab5e50a51ac834b9ec239c53f268b4700c14f19b9499ac58d8ad",
	}, {
		name:     "alternating bits",
		in:       "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: "cb6086e560b8597a85c934e46f5b6e8a445bf3f0a88e4160d7fa8d83fd10338d",
	}, {
		name:     "alternating bits 2",
		in:       "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: "9f864ca486a74eb5f546364d76d24aa93716dc78f84847aa6c1c09fca2707d77",
	}}

	for _, test := range tests {
		s := mustModNScalarWithOverflow(test.in)
		expected := mustModNScalar(test.expected)

		// Ensure calculating the multiplicative inverse of another value
		// produces the expected result.
		result := new(ModNScalar).InverseValNonConst(s)
		if !result.Equals(expected) {
			t.Errorf("%s: unexpected result -- got: %v, want: %v", test.name,
				result, expected)
			continue
		}

		// Ensure calculating the multiplicative inverse in place also produces
		// the expected result.
		result2 := new(ModNScalar).Set(s).InverseNonConst()
		if !result2.Equals(expected) {
			t.Errorf("%s: unexpected result -- got: %v, want: %v", test.name,
				result2, expected)
			continue
		}

		// Ensure algebraic properties with inverses hold.
		checkModNScalarInverseProps(t, s)
	}
}

// TestModNScalarInverseNonConstRandom ensures that calculating the
// multiplicative inverse of scalars in *non-constant* time for random values
// works as expected by also performing the same operation with big ints and
// comparing the results.
func TestModNScalarInverseNonConstRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	for i := 0; i < 100; i++ {
		// Generate big integer and mod n scalar with the same random value.
		bigIntVal, modNVal := randIntAndModNScalar(t, rng)

		// Calculate the inverse of the value using big ints.
		bigIntResult := new(big.Int).ModInverse(bigIntVal, curveParams.N)

		// Calculate the inverse of the value using a mod n scalar.
		modNValResult := new(ModNScalar).InverseValNonConst(modNVal)

		// Ensure they match.
		bigIntResultHex := fmt.Sprintf("%064x", bigIntResult)
		modNResultHex := fmt.Sprintf("%v", modNValResult)
		if bigIntResultHex != modNResultHex {
			t.Fatalf("mismatched inverse\nbig int in: %x\nscalar in: %v\n"+
				"big int result: %x\nscalar result %v", bigIntVal, modNVal,
				bigIntResult, modNValResult)
		}

		// Ensure algebraic properties with inverses hold.
		checkModNScalarInverseProps(t, modNVal)
	}
}

// checkModNScalarHalfOrderProps checks algebraic properties of the half order
// comparison.
func checkModNScalarHalfOrderProps(t *testing.T, val *ModNScalar) {
	t.Helper()

	// Exception for 0 which is the only scalar where negation does not produce
	// a distinct value.
	if val.IsZero() {
		return
	}

	// Ensure negating a scalar flips whether it is over half order.
	//
	// x > N/2 implies N-x < N/2 and vice versa.
	negation := new(ModNScalar).NegateVal(val)
	if val.IsOverHalfOrder() == negation.IsOverHalfOrder() {
		t.Errorf("negation did not flip half order -- val: %v, negation: %v",
			val, negation)
	}
}

// TestModNScalarIsOverHalfOrder ensures that scalars report whether or not they
// exceeed the half order works as expected for edge cases.
func TestModNScalarIsOverHalfOrder(t *testing.T) {
	tests := []struct {
		name     string // test description
		in       string // hex encoded test value
		expected bool   // expected result
	}{{
		name:     "zero",
		in:       "0",
		expected: false,
	}, {
		name:     "one",
		in:       "1",
		expected: false,
	}, {
		name:     "group half order - 1",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b209f",
		expected: false,
	}, {
		name:     "group half order",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a0",
		expected: false,
	}, {
		name:     "group half order + 1",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501ddfe92f46681b20a1",
		expected: true,
	}, {
		name:     "over half order limb one",
		in:       "7fffffffffffffffffffffffffffffff5d576e7357a4501edfe92f46681b20a0",
		expected: true,
	}, {
		name:     "group order - 2",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd036413f",
		expected: true,
	}, {
		name:     "group order - 1",
		in:       "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364140",
		expected: true,
	}, {
		name:     "highest limb below half order",
		in:       "7fffffffffffffffffffffffffffffff00000000000000000000000000000000",
		expected: false,
	}, {
		name:     "highest bit set",
		in:       "8000000000000000000000000000000000000000000000000000000000000000",
		expected: true,
	}, {
		name:     "alternating bits",
		in:       "a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5",
		expected: true,
	}, {
		name:     "alternating bits 2",
		in:       "5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a",
		expected: false,
	}}

	for _, test := range tests {
		s := mustModNScalarWithOverflow(test.in)
		result := s.IsOverHalfOrder()
		if result != test.expected {
			t.Errorf("%s: unexpected result -- got: %v, want: %v", test.name,
				result, test.expected)
			continue
		}

		// Ensure algebraic properties with the half order hold.
		checkModNScalarHalfOrderProps(t, s)
	}
}

// TestModNScalarIsOverHalfOrderRandom ensures that scalars report whether or
// not they exceeed the half order for random values works as expected by also
// performing the same operation with big ints and comparing the results.
func TestModNScalarIsOverHalfOrderRandom(t *testing.T) {
	// Use a unique random seed each test instance and log it if the tests fail.
	seed := time.Now().Unix()
	rng := rand.New(rand.NewSource(seed))
	defer func(t *testing.T, seed int64) {
		if t.Failed() {
			t.Logf("random seed: %d", seed)
		}
	}(t, seed)

	bigHalfOrder := new(big.Int).Rsh(curveParams.N, 1)
	for i := 0; i < 100; i++ {
		// Generate big integer and mod n scalar with the same random value.
		bigIntVal, modNVal := randIntAndModNScalar(t, rng)

		// Determine the value exceeds the half order using big ints.
		bigIntResult := bigIntVal.Cmp(bigHalfOrder) > 0

		// Determine the value exceeds the half order using a mod n scalar.
		modNValResult := modNVal.IsOverHalfOrder()

		// Ensure they match.
		if bigIntResult != modNValResult {
			t.Fatalf("mismatched is over half order\nbig int in: %x\nscalar "+
				"in: %v\nbig int result: %v\nscalar result %v", bigIntVal,
				modNVal, bigIntResult, modNValResult)
		}

		// Ensure algebraic properties with the half order hold.
		checkModNScalarHalfOrderProps(t, modNVal)
	}
}
